[project]
name = "sql-srs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "louis ROLAND", email = "louisroland9@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "black>=26.5.1",
    "duckdb>=1.5.5",
    "pylint>=4.0.9",
    "streamlit>=1.63.0",
]

[project.scripts]
sql-srs = "sql_srs:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
